### ISSUE TITLE
Error npm install

### ISSUE THREAD

**Issue by inc2734** [sass-basis/basis#80]
```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> node-sass@3.6.0 install /Users/xxx/Desktop/test/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/xxx/Desktop/test/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@3.6.0 postinstall /Users/xxx/Desktop/test/node_modules/node-sass
> node scripts/build.js

"/Users/xxx/Desktop/test/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists. 
 testing binary.
Binary is fine; exiting.

> sass-basis@4.2.0 postinstall /Users/xxx/Desktop/test/node_modules/sass-basis
> gulp build

module.js:339
    throw err;
    ^

Error: Cannot find module 'browser-sync'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/xxx/Desktop/test/node_modules/sass-basis/gulpfile.js:11:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
/Users/xxx/Desktop/test
└── (empty)

npm WARN enoent ENOENT: no such file or directory, open '/Users/xxx/Desktop/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install" "sass-basis"
npm ERR! node v4.2.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! sass-basis@4.2.0 postinstall: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sass-basis@4.2.0 postinstall script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sass-basis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sass-basis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sass-basis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxx/Desktop/test/npm-debug.log
npm ERR! code 1
```

**Comment by inc2734** [comment]
7387d46057fe4f12e4c2095f6019c38e146c63d1
